# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f3f9bccea786f5b62bf411d047b197b121565aab8324708c9f2e73ee687025e58319aeb05f441305f3240f0f9aa67cb91c8fcb8eb4a163bcd870ab1d1a15040

test:
  secret_key_base: 32effc88d7a88113eeda4711a81946bb5c21e50ad933ca90bd21928bd9886fb4368d59b8819774a070f26e623b6e84a9efb18de408dc748f269d7afbc31df9fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
